myapp/urls.py
from django.urls import path, re_path
from myapp import views

app_name = 'myapp'
urlpatterns = [
    path(r'', views.index, name='index'),
    path(r'about/', views.about, name='about'),
    path('<int:cat_no>/', views.detail, name="detail"),
    path(r'products/', views.products, name="products"),
    re_path(r'^products/(?P<prod_id>\d+)/$', views.productdetail, name="productdetail"),
    path(r'place_order/',views.place_order,name='place_order'),
    path(r'login/', views.user_login, name='login'),
    path(r'logout/', views.user_logout, name='logout'),
    path(r'myorders/', views.myorders, name='myorders'),
    path(r'register/', views.register, name='register'),
    path(r'forgot_password/', views.forgot_password, name='forgot_password'),
               ]

mysiteF22/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path(r'myapp/', include('myapp.urls')),
]

myapp/models.py
from django.db import models
import datetime
from django.contrib.auth.models import User
from django.utils import timezone
from django.core.validators import MinValueValidator, MaxValueValidator


# Create your models here.


class Category(models.Model):
    name = models.CharField(max_length=200)
    warehouse = models.CharField(max_length=200, null=True, blank=True)

    def __str__(self):
        return self.name


class Product(models.Model):
    category = models.ForeignKey(Category, related_name='products', on_delete=models.CASCADE)
    name = models.CharField(max_length=200)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    stock = models.PositiveIntegerField(default=100, validators=[MinValueValidator(0), MaxValueValidator(1000)])
    available = models.BooleanField(default=True)
    description = models.TextField(blank=True, null=True)
    interested = models.PositiveIntegerField(default=0)

    def __str__(self):
        return self.name

    def refill(self):
        self.stock = self.stock + 100
        return self.stock



class Client(User):
    PROVINCE_CHOICES = [('AB', 'Alberta'), ('MB', 'Manitoba'), ('ON', 'Ontario'), ('QC', 'Quebec'),]
    company = models.CharField(max_length=50, blank=True, null=True)
    shipping_address = models.CharField(max_length=300, null=True, blank=True)
    city = models.CharField(max_length=20, default='Windsor')
    province=models.CharField(max_length=2, choices=PROVINCE_CHOICES, default='ON')
    interested_in = models.ManyToManyField(Category)
    image = models.ImageField(upload_to='images/', blank=True, null=True)

    def interested_in_list(self):
        return ", ".join([str(p) for p in self.interested_in.all()])
        # return self.interested_in.all()
    def __str__(self):
        return self.username

class Order(models.Model):
    valid_val = [(0, 'Order Cancelled'), (1, 'Order Placed'), (2, 'Order Shipped'),(3, 'Order Delivered')]
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    client = models.ForeignKey(Client, on_delete=models.CASCADE)
    num_units = models.PositiveIntegerField(default=1)
    order_status = models.IntegerField(default=1, choices=valid_val)
    status_date = models.DateField(default=timezone.now)

    def __str__(self):
        return f'{self.client} ordered {self.num_units} of {self.product}'

    def total_cost(self):
        return self.product.price * self.num_units

myapp/forms.py
from django import forms
from myapp.models import Order, Client


class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ['client', 'product', 'num_units']
        widgets = {'client': forms.RadioSelect}
        labels = {'num_units': u'Quantity', 'client': u'Client Name'}


class InterestForm(forms.Form):
    interested = forms.BooleanField(label="Interested", widget=forms.RadioSelect(choices=[(1, 'Yes'), (0, 'No'), ]), required=False)
    quantity = forms.IntegerField(label="Quantity", min_value=1, initial=1)
    comments = forms.CharField(label="Additional Comments", widget=forms.Textarea, required=False)

class RegisterForm(forms.ModelForm):
    class Meta:
        model = Client
        fields = ['username', 'password', 'email', 'first_name', 'last_name', 'interested_in']
        widgets = {'interested_in': forms.CheckboxSelectMultiple, 'password': forms.PasswordInput}
        labels = {'interested_in': 'Select the topics that you are interested in'}


class ForgotPasswordForm(forms.Form):
    Email = forms.EmailField()

    def __str__(self):
        return self.Email

myapp/views.py
# Import necessary classes
import random
import string

from django.contrib import messages
from django.contrib.auth.hashers import make_password
from django.contrib.auth.models import Group
from django.core.mail import send_mail
from django.db.models import F
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, redirect
from django.urls import reverse
from django.utils import timezone

from mysiteF22.settings import EMAIL_HOST_USER
from .forms import *
from .models import Category, Product, Client, Order
from django.shortcuts import get_object_or_404


# Create your views here.

# def index(request):
#     cat_list = Category.objects.all().order_by('id')[:10]
#     response = HttpResponse()
#     heading1 = '<p>' + 'List of categories: ' + '</p>'
#     response.write(heading1)
#     for category in cat_list:
#         para = '<p>'+ str(category.id) + ': ' + str(category) + '</p>'
#         response.write(para)
#
#     prod_list = Product.objects.all().order_by('-price')[:20]
#     heading2 = '<p>' + 'List of products: ' + '</p>'
#     response.write(heading2)
#     for prod in prod_list:
#         para1 = '<p>' + str(prod.name) + ': $' + str(prod.price) + '</p>'
#         response.write(para1)
#
#     return response

def index(request):
    cat_list = Category.objects.all().order_by('id')[:10]
    return render(request, 'myapp/index.html', {'cat_list': cat_list})


def about(request):
    if 'about_visits' in request.COOKIES.keys():
        number_visits = request.COOKIES['about_visits']
        number_visits = int(number_visits) + 1
    else:
        number_visits = 1

    response = render(request, 'myapp/about.html', {'number_visits': number_visits})
    response.set_cookie('about_visits', value=number_visits, max_age=300)
    # response = HttpResponse()
    # head = '<h1>' + 'This is an Online Store APP.' + '</h1>'
    # response.write(head)
    return response
    # return render(request, 'myapp/about.html')


def detail(request, cat_no):
    lis = []
    response = HttpResponse()
    prod_list = Product.objects.filter(category_id=cat_no)
    # print(prod_list)
    cate = Category.objects.get(id=cat_no).name
    ware = Category.objects.get(id=cat_no).warehouse
    if (len(prod_list) == 0):
        get_object_or_404(Product.objects.filter(category_id=cat_no))
    heading2 = '<p>' + 'List of products: ' + '</p>'
    response.write(heading2)
    for prod in prod_list:
        prodl = '<p>' + str(prod.name) + ': $' + str(prod.price) + '</p>'
        lis.append(str(prod.name))
        response.write(prodl)
    # return response
    return render(request, 'myapp/detail.html', {'prod_list': prod_list, 'cate': cate, 'ware': ware})


def products(request):
    prodlist = Product.objects.all().order_by('id')[:10]
    return render(request, 'myapp/products.html', {'prodlist': prodlist})


def place_order(request):
    msg = ''
    prodlist = Product.objects.all()
    if request.method == 'POST':
        form = OrderForm(request.POST)
        if form.is_valid():
            order = form.save(commit=False)
            if order.num_units <= order.product.stock:
                order.product.stock -= order.num_units
                order.product.save()
                order.save()
                msg = 'Your order has been placed successfully.'
            else:
                msg = 'We do not have sufficient stock to fill your order.'
            return render(request, 'myapp/order_response.html', {'msg': msg})
    else:
        form = OrderForm()
    return render(request, 'myapp/placeorder.html', {'form': form, 'msg': msg, 'prodlist': prodlist})


def productdetail(request, prod_id):
    if len(Product.objects.filter(id=prod_id)) == 0:
        msg = "Product not found"
        return render(request, 'myapp/productdetail.html', {'msg': msg})

    name = Product.objects.get(id=prod_id).name
    price = Product.objects.get(id=prod_id).price
    interested = Product.objects.get(id=prod_id).interested

    if request.method == 'POST':
        form = InterestForm(request.POST)
        if form.is_valid():
            if request.POST.get('interested') == '1':
                Product.objects.filter(id=prod_id).update(interested=F('interested') + 1)
        return redirect('myapp:index')
    else:
        form = InterestForm()
    return render(request, 'myapp/productdetail.html',
                  {'form': form, 'name': name, 'price': price, 'interested': interested})


from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required, user_passes_test  # Create your views here.


def user_login(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user:
            if user.is_active:
                login(request, user)
                if 'last_login' in request.session:
                    messages.success(request, 'Last login date and time: ' + str(request.session['last_login']))
                else:
                    request.session['last_login'] = str(timezone.now())
                    # print(request.session['last_login'])
                    messages.success(request, "Your last login was more than 1 hour ago")

                request.session['last_login'] = str(timezone.now())
                request.session['username'] = username
                request.session['user_first_name'] = user.first_name
                request.session['user_last_name'] = user.last_name
                request.session.set_expiry(3600)

                # return HttpResponseRedirect(reverse('myapp:index'))
                # return HttpResponseRedirect(reverse('myapp:myorders'))
                if 'next' in request.POST:
                    return redirect(request.POST.get('next'))
                else:
                    return HttpResponseRedirect(reverse('myapp:index'))
                # return redirect(request.GET.get('next', 'myapp:index'))
            else:
                return HttpResponse('Your account is disabled.')
        else:
            return HttpResponse('Invalid login details.')
    else:
        return render(request, 'myapp/login.html')


@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse(('myapp:index')))


def register(request):
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            userForm = form.save(commit=False)
            userForm.password = make_password(form.cleaned_data['password'])
            userForm.save()
            form.save_m2m()
            # g = Group.objects.get(name='Client')
            # g.user_set.add(userForm)
            print(userForm)
            return HttpResponseRedirect(reverse('myapp:index'))
        else:
            return HttpResponse('Error during registration')
    else:
        form = RegisterForm()
        return render(request, 'myapp/register.html', {'form': form})



@login_required(login_url='myapp:login')
def myorders(request):
    client_list = Client.objects.all().order_by('id')
    client_list = [i.username for i in client_list]

    if f'{request.user}' in client_list:
        order_list = Order.objects.filter(client__username=request.user)
        return render(request, 'myapp/myorders.html', {"order_list": order_list})
    else:
        return HttpResponse('You are not a registered client!')

def forgot_password(request):
    if request.method == 'POST':
        form = ForgotPasswordForm(request.POST)
        if form.is_valid():
            random_password = ''.join(random.choice(string.ascii_letters) for i in range(10))
            password = make_password(random_password)
            Client.objects.filter(email=form.cleaned_data['Email']).update(password=password)

            subject = 'New Password'
            message = 'Your new password is ' + random_password
            recipient = form.cleaned_data['Email']
            send_mail(subject,message,EMAIL_HOST_USER,[recipient],fail_silently=False)
            return HttpResponse('A password has been sent to your inbox')
        else:
            return HttpResponse('Incorrect details')
    else:
        form = ForgotPasswordForm()
        return render(request,'myapp/forgot_password.html',{'form': form})

myapp/templates/myapp/about.html
{% extends 'myapp/base.html' %}

{% block body_block %}

    <h3>This is an Online Store APP</h3>
    <p>
    Number of visits: {{ number_visits }}
    </p>
{% endblock %}

myapp/templates/myapp/about0.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>About</title>
</head>
<body>
    <h3>This is an Online Store APP</h3>
</body>
</html>

myapp/templates/myapp/base.html
<!DOCTYPE html>
{% load static %}
<html>
    <head>
    <!-- CSS only -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
        <link rel="stylesheet" type="text/css" href="{% static 'myapp/style.css' %}"/>
        <title>Online Store APP - {% block title %}Welcome!{% endblock %}</title>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
        <a class="navbar-brand" href="#">Online Store APP</a>
         {% if 'username' in request.session %}
                    <li class="hbar1"><a href="{% url 'myapp:logout' %}">Logout</a></li>
                    <li class="hbar1"><a href="{% url 'myapp:myorders' %}">My Orders</a></li>
                {% else %}
                    <li class="hbar1"><a href="{% url 'myapp:register' %}">Register Here</a></li>
                    <li class="hbar1"><a href="{% url 'myapp:login' %}">Login</a></li>
                {% endif %}
    </div>
</nav>
    </head>
    <body>
       <div>
           {% if 'user_first_name' in request.session %}
                <h1 class="text-center well-sm">Hello {{ request.session.user_first_name }} </h1>
            {% else %}
                <h1 class="text-center well-sm" >Hello User</h1>
            {% endif %}
           {% block body_block %}*** {% endblock %}
       </div>
       <hr />
       <div>
           <ul>
               <li class="hbar1"><a href="/myapp/about/">Find out about this site</a></li>
               <li class="hbar1"><a href = "{% url 'myapp:products' %}">Click here to return to Products page</a><br/></li>
               <li class="hbar1"><a href = "{% url 'myapp:index' %}">Click here to return to main page</a><br/></li>
           </ul>
       </div>
    </body>
</html>

myapp/templates/myapp/detail.html
{% extends 'myapp/base.html' %}
{% block body_block %}
<h1> Category: {{ cate }}</h1>
<h1> Warehouse: {{ ware }}</h1>

{% for prod in prod_list %}
    <li> {{ prod.name}} </li>
    {% endfor %}
{% endblock %}

myapp/templates/myapp/detail0.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Detail</title>
</head>
<body>
<h1> Category: {{ cate }}</h1>
<h1> Warehouse: {{ ware }}</h1>

{% for prod in prod_list %}
    <li> {{ prod.name}} </li>
    {% endfor %}
</body>
</html>

myapp/templates/myapp/forgot_password.html
{% extends 'myapp/base.html' %}
{% block body_block %}
 <h1>Site Forgot Password</h1>
    <form action="{% url 'myapp:forgot_password' %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input class = "btn btn-success" type="submit" name="submit1" value="Send email" />
    </form>

{% endblock %}

myapp/templates/myapp/index.html
{% extends 'myapp/base.html' %}
{% block body_block %}
    {% if cat_list %}
    <h2>List of Categories</h2>
    <ol>
    {% for cat in cat_list %}
        <li> <a href="{{ cat.id }}">{{ cat.name}}</a> </li>
    {% endfor %}
    </ol>
    {% else %}
    <strong>There are no available categories!</strong>
    {% endif %}

    {% for message in messages %}
    <p>{{ message }}</p>
    {% endfor %}
{#    <p><a href="/myapp/about">About page</a></p>#}
{#    <a href="{% url ‘myapp:about ’%}">About Page</a>#}
{#    <a href = "{% url 'myapp:index' %}">Click here to return to main page</a>#}
{% endblock %}

myapp/templates/myapp/index0.html
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title>Online Store APP</title>
</head>
<body>
    {% if cat_list %}
    <h2>List of Categories</h2>
    <ol>
    {% for cat in cat_list %}
    <li> {{ cat.name}} </li>
    {% endfor %}
    </ol>
    {% else %}
    <strong>There are no available categories!</strong>
    {% endif %}
    <p><a href="/myapp/about">About page</a></p>
</body>
</html>

myapp/templates/myapp/myorders.html
{% extends 'myapp/base.html' %}
{% block body_block %}

    <table class="table table-hover">
            <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Product</th>
                <th scope="col">Number of units</th>
                <th scope="col">Status Date</th>
            </tr>
            </thead>
            <tbody>
            {% for item in order_list %}
                <tr>
                    <th scope="row">{{ forloop.counter }}</th>
                    <td>{{ item.product }}</td>
                    <td>{{ item.num_units }}</td>
                    <td>{{ item.status_date }}</td>
                </tr>

            {% endfor %}
            </tbody>
        </table>

{% endblock %}

myapp/templates/myapp/order_response.html
{% extends 'myapp/base.html' %}
{% block body_block %}
    
    <h3>{{ msg }}</h3>
</form>
{% endblock %}

myapp/templates/myapp/placeorder.html
{% extends 'myapp/base.html' %}
{% block body_block %}
    <h3>List of Products</h3>
    {% for prod in prodlist %}
        <li> <a href="{{ prod.id }}">{{ prod.name}}</a> </li>
    {% endfor %}
    <form action= "{% url 'myapp:place_order' %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
{#    <input type="submit" value="Submit">#}
    <button class = "btn btn-success" type="submit" value="placeorder" >Place Order</button>
</form>


{% endblock %}

myapp/templates/myapp/productdetail.html
{% extends 'myapp/base.html' %}
{% block body_block %}
    <p>Name: {{ name }}</p>
    <p>Interested: {{ interested }}</p>
    <p>Price: {{ price }}</p>

    <h5>{{ msg }}</h5>

    <form action= "" method="post">
    {% csrf_token %}
    {{ form.as_p }}
{#    <input type="submit" value="Submit">#}
    <button class = "btn btn-success" type="submit" value="productdetail" >Submit</button>
</form>

{% endblock %}

myapp/templates/myapp/products.html
{% extends 'myapp/base.html' %}
{% block body_block %}
    <h2>List of Products</h2>
    <ol>
    {% for prod in prodlist %}
{#        <li> {{ prod.name }} </a> </li>#}
        <li> <a href="{{ prod.id }}">{{ prod.name}}</a> </li>
    {% endfor %}
    </ol>
{#    <p><a href="/myapp/about">About page</a></p>#}
{#    <a href="{% url ‘myapp:about ’%}">About Page</a>#}
{#    <a href = "{% url 'myapp:index' %}">Click here to return to main page</a>#}
{#    Update products.html to add a link to place_order page using url namespacing tag#}
    <a href = "{% url 'myapp:place_order' %}">Click here to place order</a>
{% endblock %}

myapp/templates/myapp/register.html
{% extends 'myapp/base.html' %}
{% block body_block %}
     <h1>Site Registration</h1>
    <form action="{% url 'myapp:register' %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button class = "btn btn-success" type="submit" name="submit1" class="btn btn-success" value="Register" style="margin: 10px">Register</button>

    </form>

{% endblock %}